### ISSUE TITLE
Zero-cost at runtime / ‘noassert’ perf build?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [janestreet/ppx_assert#2]
Hi! I'm an OCaml newbie, so forgive me if this is a super-stupid question — but coming from JS-land, I'm used to using tools like the [babel-plugin-espower](https://github.com/power-assert-js/babel-plugin-espower) plugin from [power-assert](https://github.com/power-assert-js/power-assert#readme) toolkit to preprocess invariant/boundary-checking assertions out of the source entirely before compilation to the ‘production’ build.

I can't quite tell if `[%test_result: int]` works like this, outside of ppx_inline_test's explicit `let%test` expressions? If I start using this, is there a methodology (I'm using JBuilder) to preprocess them out entirely at build-time?

Thanks for your time.

**Comment by ghost** [comment]
There is currently no option in ppx_assert to drop such tests at runtime. However, these are usually used inside inline tests and there is an option to drop inline tests. If using Dune (the new name for JBuilder), you can write this in your jbuild file:

```scheme
(library
 (...
  (preprocess ((ppx_inline_test ppx_assert -inline-test-drop)))))
```

BTW, note that this is an old project. While we still use it in a few places, for unit tests we have almost entirely switched to [testing with expectation](https://blog.janestreet.com/testing-with-expectations/). This workflow is [supported by Dune](https://discuss.ocaml.org/t/jbuilder-inline-tests/1741), so I encourage you to check it out.

**Comment by xclerc** [comment]
(Documentation clarified by https://github.com/janestreet/ppx_assert/commit/7255f6cf2a40c529cef5e8278d0ef8263b0a86e1.)
